---
title: "IPA Data Preparation Myotubes "
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup}
suppressPackageStartupMessages({if (!require("BiocManager", quietly = TRUE))
    install.packtimepoints("BiocManager")
})

pacman::p_load(data.table, tidyverse, readr, DESeq2, tximport, apeglm)

library(org.Nviridescens.eg.db)
```



#PREPARING DATA

```{r}
# Load in annotations

annotations_combined <- fread("C:/Users/gevd910d/Desktop/A1 Analysis/Combined Annotations Nvir/Nvir_annotations_combined.csv", header = TRUE)

# Katia annotations
annotations <- read.csv("C:/Users/gevd910d/Desktop/A1 Analysis/Nvir_Annotations/Nvir Latest Annotation Katia/Nvir_annotations_MT_Katia_final.csv", header = TRUE)

head(annotations)
```


```{r}
# Read in salmon abundance files

dir <- "C:/Users/gevd910d/Desktop/A1 Analysis/salmon_MT_Katia_reference"

#list.files(dir)
```


#1 All vs 0h
```{r}
coldata <- read.table(file.path(dir, "samples.txt"), header = TRUE)

coldata <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "0"), # Dediff as the interesting one
         differentiation = factor(differentiation))
         
rownames(coldata) <- coldata$replicate
```


```{r}
files <- file.path(dir, coldata$filename) # List of all of your files
all(file.exists(files))

names(files) <- coldata$replicate # Name files based on metadata
```

```{r}
tx2gene <- read.csv(file.path(dir, "tx2gene_nvir_katia.csv"))



txi <- tximport(files, 
                type = "salmon", 
                tx2gene = tx2gene) 

counts <- txi$abundance

# QC
all(rownames(coldata) == colnames(txi))
```



```{r}
# Create DESEq2 object

dds <- DESeqDataSetFromTximport(txi,
                                   colData = coldata,
                                   design = ~ timepoint)

# Pre-filter -> at least 10 counts in 3 samples. N = minimal number of samples where non-zero counts would be considered interesting

keep <- rowSums(counts(dds) >= 10) >= 3
dds <- dds[keep,]

dds <- DESeq(dds) 
```



```{r}
# Takes the annotation of isoforms with the most GO annotations
annotations_gid <- annotations

annotations_gid$X.GO_IP[is.na(annotations_gid$X.GO_IP)] <- 0

# Group by GENEID and filter the rows where X.GO_IP is the largest 

setDT(annotations_gid)

# Dplyr takes too long, this is more efficient
annotations_gid <- annotations_gid[, .SD[which.max(X.GO_IP)], by = GENEID]
```


```{r}
coeff_1 <-  resultsNames(dds)[-1]

# Initialize a list to store results
results_1 <- list()

# Loop through each coefficient
for (coef in coeff_1) {
  
  res <- lfcShrink(dds, coef = coef, type = "apeglm")
  
  res_df <- res %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
  # Create a dynamic variable name
  var_name <- paste0("res_", gsub("timepoint_", "", coef))
  
  # Rename columns except GENEID
  colnames(res_df)[-1] <- paste0(colnames(res_df)[-1], "_", gsub("timepoint_", "", coef))
  
  assign(var_name, res_df)
  
  results_1[[var_name]] <- res_df
}


results_1_IPA <- Reduce(function(x, y) left_join(x, y, by = "GENEID"), results_1)

results_1_IPA <- results_1_IPA %>%
  left_join(annotations_gid, by = "GENEID")

results_1_IPA$Uniprot <- results_1_IPA$stitle_SP


write.csv(results_1_IPA, file = "IPA Results All vs 0h.csv", row.names = FALSE)
```

```{r}
# Save differentiation part only

results_diff <- results_1[1:3]


results_diff <- Reduce(function(x, y) left_join(x, y, by = "GENEID"), results_diff)

results_diff <- results_diff %>%
  left_join(annotations_gid, by = "GENEID")

results_diff$Uniprot <- results_diff$stitle_SP


write.csv(results_diff, file = "IPA Results Differentiation Myotubes.csv", row.names = FALSE)
```




#2 Sequential Comparisons

apeglm doesn't support coefficients, have to re-level and rerun each time

```{r}
coldata_2 <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "8"))



dds_2 <- DESeqDataSetFromTximport(txi,
                                   colData = coldata_2,
                                   design = ~ timepoint)

keep_2 <- rowSums(counts(dds_2) >= 10) >= 3
dds_2 <- dds_2[keep_2,]

dds_2 <- DESeq(dds_2) 

resultsNames(dds_2)



res_72_vs_8 <- lfcShrink(dds_2, coef = "timepoint_72_vs_8", type = "apeglm")
  
res_72_vs_8 <- res_72_vs_8 %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
colnames(res_72_vs_8)[-1] <- paste0(colnames(res_72_vs_8)[-1], "_72_vs_8")
```





```{r}
coldata_3 <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "72"))




dds_3 <- DESeqDataSetFromTximport(txi,
                                   colData = coldata_3,
                                   design = ~ timepoint)

keep_3 <- rowSums(counts(dds_3) >= 10) >= 3
dds_3 <- dds_3[keep_3,]

dds_3 <- DESeq(dds_3) 

resultsNames(dds_3)




res_120_vs_72 <- lfcShrink(dds_3, coef = "timepoint_120_vs_72", type = "apeglm")
  
res_120_vs_72 <- res_120_vs_72 %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
colnames(res_120_vs_72)[-1] <- paste0(colnames(res_120_vs_72)[-1], "_120_vs_72")
```







```{r}
coldata_4 <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "120"))




dds_4 <- DESeqDataSetFromTximport(txi,
                                   colData = coldata_4,
                                   design = ~ timepoint)

keep_4 <- rowSums(counts(dds_4) >= 10) >= 3
dds_4 <- dds_4[keep_4,]

dds_4 <- DESeq(dds_4) 

resultsNames(dds_4)





res_128_vs_120 <- lfcShrink(dds_4, coef = "timepoint_128_vs_120", type = "apeglm")
  
res_128_vs_120 <- res_128_vs_120 %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
colnames(res_128_vs_120)[-1] <- paste0(colnames(res_128_vs_120)[-1], "_128_vs_120")
```










```{r}
coldata_5 <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "128"))





dds_5 <- DESeqDataSetFromTximport(txi,
                                   colData = coldata_5,
                                   design = ~ timepoint)

keep_5 <- rowSums(counts(dds_5) >= 10) >= 3
dds_5 <- dds_5[keep_5,]

dds_5 <- DESeq(dds_5) 

resultsNames(dds_5)





res_144_vs_128 <- lfcShrink(dds_5, coef = "timepoint_144_vs_128", type = "apeglm")
  
res_144_vs_128 <- res_144_vs_128 %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
colnames(res_144_vs_128)[-1] <- paste0(colnames(res_144_vs_128)[-1], "_144_vs_128")
```





```{r}
coldata_6 <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "144"))




dds_6 <- DESeqDataSetFromTximport(txi,
                                   colData = coldata_6,
                                   design = ~ timepoint)

keep_6 <- rowSums(counts(dds_6) >= 10) >= 3
dds_6 <- dds_6[keep_6,]

dds_6 <- DESeq(dds_6) 

resultsNames(dds_6)




res_168_vs_144 <- lfcShrink(dds_6, coef = "timepoint_168_vs_144", type = "apeglm")
  
res_168_vs_144 <- res_168_vs_144 %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
colnames(res_168_vs_144)[-1] <- paste0(colnames(res_168_vs_144)[-1], "_168_vs_144")
```




```{r}
results_2 <- list(
  res_8_vs_0,
  res_72_vs_8,
  res_120_vs_72,
  res_128_vs_120,
  res_144_vs_128,
  res_168_vs_144
)


results_2_IPA <- Reduce(function(x, y) left_join(x, y, by = "GENEID"), results_2)

results_2_IPA <- results_2_IPA %>%
  left_join(annotations_gid, by = "GENEID")

results_2_IPA$Uniprot <- results_2_IPA$stitle_SP


write.csv(results_2_IPA, file = "IPA Results Sequential Comparisons Myotubes.csv", row.names = FALSE)
```






#3 Dediff Separately
```{r}
coldata_dediff <- coldata %>%
  mutate(timepoint = relevel(factor(timepoint), ref = "120"))




dds_dediff <- DESeqDataSetFromTximport(txi,
                                   colData = coldata_dediff,
                                   design = ~ timepoint)

keep_dediff <- rowSums(counts(dds_dediff) >= 10) >= 3
dds_dediff <- dds_dediff[keep_dediff,]

dds_dediff <- DESeq(dds_dediff) 

resultsNames(dds_dediff)
```




# Saving Results
```{r}
coeff_dediff <-  resultsNames(dds_dediff)[5:7]

# Initialize a list to store results
results_dediff <- list()

# Loop through each coefficient
for (coef in coeff_dediff) {
  
  res <- lfcShrink(dds_dediff, coef = coef, type = "apeglm")
  
  res_df <- res %>% 
    as_tibble(rownames = "GENEID") %>%
    filter(!is.na(padj))
  
  # Create a dynamic variable name
  var_name <- paste0("res_", gsub("timepoint_", "", coef))
  
  # Rename columns except GENEID
  colnames(res_df)[-1] <- paste0(colnames(res_df)[-1], "_", gsub("timepoint_", "", coef))
  
  assign(var_name, res_df)
  
  results_dediff[[var_name]] <- res_df
}


results_dediff_IPA <- Reduce(function(x, y) left_join(x, y, by = "GENEID"), results_dediff)

results_dediff_IPA <- results_dediff_IPA %>%
  left_join(annotations_gid, by = "GENEID")

results_dediff_IPA$Uniprot <- results_dediff_IPA$stitle_SP


write.csv(results_dediff_IPA, file = "IPA Results Dediff.csv", row.names = FALSE)
```


# 4 Diff/Dediff
```{r}
results_diff_only <- read.csv(file = "IPA Results Diff Only.csv")




results_4_IPA <- results_diff_only %>%
  left_join(results_dediff_IPA, by = "GENEID")

write.csv(results_4_IPA, file = "IPA Results Diff (vs 0h) Dediff (vs 5d).csv", row.names = FALSE)
```




#END
```{r}
sessionInfo()
```

